
language: c

os:
    - linux

compiler:
    - clang
    - gcc

cache:
    directories:
        - llvm-fastcomp
        - protobuf

before_install:
    - (if test -d llvm-fastcomp/bin; then echo OK; else
           git clone https://github.com/kripken/emscripten-fastcomp &&
           git clone https://github.com/kripken/emscripten-fastcomp-clang emscripten-fastcomp/tools/clang &&
           mkdir emscripten-fastcomp/build &&
           cd emscripten-fastcomp/build &&
           LDFLAGS="-s" CFLAGS="-Os" CXXFLAGS="-Os" cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/llvm-fastcomp -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;JSBackend" -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF &&
           make -j4 &&
           make install;
       fi)
    - (if ! test -d protobuf/lib; then git clone --single-branch --branch master --depth 1 https://github.com/google/protobuf protobuf-src && cd protobuf-src && ./autogen.sh && ./configure --prefix=$TRAVIS_BUILD_DIR/protobuf && make && make install; fi)

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - gcc-4.8
            - g++-4.8
            - clang
            - cmake
            - autopoint
            - python-lxml

before_script:
    - NOCONFIGURE=1 ./autogen.sh

script:
    - ./configure CC="gcc-4.8" CXX="g++-4.8" PKG_CONFIG_PATH="$TRAVIS_BUILD_DIR/protobuf/lib/pkgconfig" && make
