
language: c

os:
    - linux

compiler:
    - clang
    - gcc

cache:
    directories:
        - emsdk_portable
        - protobuf

before_install:
    - (if ! test -f emsdk_portable/emsdk; then wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz && tar -xvf *.tar.gz && cd emsdk_portable && ./emsdk update && ./emsdk install latest fi)
    - (if ! test -d protobuf/lib; then git clone --single-branch --branch master --depth 1 https://github.com/google/protobuf protobuf-src && cd protobuf-src && ./autogen.sh && ./configure --prefix=$TRAVIS_BUILD_DIR/protobuf && make && make install; fi)

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - clang
            - autopoint
            - python-lxml

before_script:
    - NOCONFIGURE=1 ./autogen.sh

script:
    - ./configure CC="gcc-4.8" CXX="g++-4.8" PKG_CONFIG_PATH="$TRAVIS_BUILD_DIR/protobuf/lib/pkgconfig" && make
