
language: c

os:
    - linux

compiler:
    - clang
    - gcc

cache:
    directories:
        - emsdk

before_install:
    - (if ! test -d ./emsdk; then mkdir emsdk; cd emsdk; wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz; unzip *.zip; chmod +x ./emsdk; ./emsdk update; fi)

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - clang

before_script:
    - NOCONFIGURE=1 ./autogen.sh

script:
    - ./configure CC="gcc-4.8" CXX="g++-4.8" && make
