
language: c

os:
    - linux

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - clang

before_script:
    - NOCONFIGURE=1 ./autogen.sh

script:
    - ./configure CC="gcc-4.8" CXX="g++-4.8" && make
